const {app,BrowserWindow}=require('electron');
const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');app.setPath('userData',path.join(root,'artifacts','rooms-smoke-profile'));
app.whenReady().then(async()=>{
  let win;
  try {
    await fs.mkdir(path.join(root,'artifacts'),{recursive:true});
    win=new BrowserWindow({show:false,width:1600,height:1000,webPreferences:{preload:path.join(root,'desktop','preload.cjs'),sandbox:true,contextIsolation:true,nodeIntegration:false,backgroundThrottling:false}});win.setMenuBarVisibility(false);
    const errors=[];win.webContents.on('console-message',e=>{if(e.level==='error')errors.push(e.message);});
    const js=async code=>{try{return await win.webContents.executeJavaScript(code);}catch(error){throw Error(`${error.message}\nScript: ${code.slice(0,500)}\nRenderer: ${errors.join(' | ')}`);}},frame=()=>js('new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))');
    const auto=async()=>{await js("document.querySelector('[data-room-action=auto-distribute]').click()");await js("new Promise((resolve,reject)=>{const started=Date.now(),timer=setInterval(()=>{if(!document.querySelector('[data-room-action=auto-distribute]').disabled){clearInterval(timer);resolve();}else if(Date.now()-started>20000){clearInterval(timer);reject(Error('Auto timeout'));}},25);})");};
    const state=()=>js(`JSON.parse(localStorage.getItem('klaslokaal-v1'))`),shot=async name=>{await frame();await fs.writeFile(path.join(root,'artifacts',name),(await win.webContents.capturePage()).toPNG());};
    const canvasClick=async(gx,gy)=>{const p=await js(`(()=>{const svg=document.querySelector('#layout-grid'),p=new DOMPoint(40+${gx}*32+8,64+${gy}*32+8).matrixTransform(svg.getScreenCTM());return {x:Math.round(p.x),y:Math.round(p.y)};})()`);win.webContents.sendInputEvent({type:'mouseDown',...p,button:'left',clickCount:1});win.webContents.sendInputEvent({type:'mouseUp',...p,button:'left',clickCount:1});await frame();};
    await win.loadFile(path.join(root,'src','index.html'));
    await js(`(async()=>{const e=await import('./engine.mjs'),s=e.defaults();s.students=e.sampleStudents().slice(0,6);s.name='Lokalenproef';localStorage.setItem('klaslokaal-v1',JSON.stringify(s));})()`);await win.loadFile(path.join(root,'src','index.html'));
    assert.equal((await state()).rooms.length,1);assert.equal(await js(`document.querySelectorAll('#room .bench').length`),95);
    await js(`document.querySelector('[data-tab="rooms"]').click();document.querySelector('[data-room-action="new"]').click();document.querySelector('#new-room-name').value='Lokaal 3.12';document.querySelector('#new-room-template').value='empty';document.querySelector('#room-dialog-save').click();`);
    assert.ok(await js(`!!document.querySelector('#layout-grid')`));
    await js(`document.querySelector('[data-editor-action="student"]').click();`);await canvasClick(0,6);await js(`document.querySelector('[data-editor-action="rotate"]').click();`);
    assert.equal(await js(`document.querySelector('#bench-facing').value`),'left');assert.equal(await js(`document.querySelector('[data-grid-bench]').querySelectorAll('.grid-seat-code').length`),2);
    // Actual pointer drag snaps a table to the next bank row (first row starts at 1).
    const dragPoint=await js(`(()=>{const r=document.querySelector('[data-grid-bench] rect').getBoundingClientRect();return {x:Math.round(r.x+r.width/2),y:Math.round(r.y+r.height/2)};})()`);
    win.webContents.sendInputEvent({type:'mouseMove',...dragPoint});win.webContents.sendInputEvent({type:'mouseDown',...dragPoint,button:'left',clickCount:1});win.webContents.sendInputEvent({type:'mouseMove',x:dragPoint.x,y:dragPoint.y+168});win.webContents.sendInputEvent({type:'mouseUp',x:dragPoint.x,y:dragPoint.y+224,button:'left',clickCount:1});await frame();
    assert.equal(await js(`document.querySelector('#bench-gy').value`),'7');
    await js(`document.querySelector('[data-editor-action="undo"]').click()`);assert.equal(await js(`document.querySelector('#bench-gy').value`),'1');await js(`document.querySelector('[data-editor-action="redo"]').click()`);assert.equal(await js(`document.querySelector('#bench-gy').value`),'7');
    await js(`document.querySelector('[data-editor-action="copy"]').click();document.querySelector('#bench-capacity').value='2';document.querySelector('#bench-capacity').dispatchEvent(new Event('change'));document.querySelector('[data-editor-action="teacher"]').click();`);
    await canvasClick(12,0);
    assert.equal(await js(`document.querySelector('#bench-capacity')===null`),true);await shot('desktop-room-editor.png');
    await js(`document.querySelector('[data-editor-action="save"]').click()`);
    let s=await state(),a=s.rooms.find(r=>r.name==='Lokaal 3.12');assert.equal(a.layout.benches.filter(b=>b.kind==='student').length,2);assert.equal(a.layout.benches.filter(b=>b.kind==='teacher').length,1);assert.equal(a.layout.benches.filter(b=>b.kind==='student').reduce((n,b)=>n+b.capacity,0),4);
    await js(`document.querySelector('[data-room-copy="${a.id}"]').click();document.querySelector('#room-name').value='Lokaal 4.05';document.querySelector('#room-dialog-save').click();document.querySelector('[data-room-template="${a.id}"]').click();document.querySelector('#room-name').value='Mijn opstelling';document.querySelector('#room-dialog-save').click();`);
    s=await state();const b=s.rooms.find(r=>r.name==='Lokaal 4.05');assert.equal(s.roomTemplates.length,1);assert.deepEqual(b.assignments,{});
    await js(`document.querySelector('[data-tab="distribution"]').click();const box=document.querySelector('[data-room-participates="standaardlokaal"]');box.checked=false;box.dispatchEvent(new Event('change'));`);
    for(const id of [a.id,b.id])await js(`document.querySelector('[data-room-participates="${id}"]').checked=true;document.querySelector('[data-room-participates="${id}"]').dispatchEvent(new Event('change'));`);
    await auto();s=await state();assert.equal(Object.values(s.studentRooms).filter(id=>id===a.id).length,3);assert.equal(Object.values(s.studentRooms).filter(id=>id===b.id).length,3);assert.equal(Object.keys(s.rooms.find(r=>r.id===a.id).assignments).length,3);assert.equal(Object.keys(s.rooms.find(r=>r.id===b.id).assignments).length,3);assert.equal(await js("document.querySelector('#distribution-reviewed')"),null);await shot('desktop-room-distribution.png');
    const dragPupil=async(id,destination)=>{const points=await js(`(()=>{const student=document.querySelector('[data-room-pupil="${id}"]'),room=document.querySelector('[data-drop-room="${destination}"]');student.scrollIntoView({block:'nearest'});const a=student.getBoundingClientRect(),b=room.querySelector('.room-participates').getBoundingClientRect();return {from:{x:Math.round(a.x+a.width/2),y:Math.round(a.y+a.height/2)},to:{x:Math.round(b.x+b.width/2),y:Math.round(b.y+b.height/2)}};})()`);win.webContents.sendInputEvent({type:'mouseDown',...points.from,button:'left',clickCount:1});win.webContents.sendInputEvent({type:'mouseMove',...points.to});win.webContents.sendInputEvent({type:'mouseUp',...points.to,button:'left',clickCount:1});await frame();};
    const firstRoom=s.studentRooms['demo-0'],secondRoom=firstRoom===a.id?b.id:a.id;await dragPupil('demo-0',secondRoom);assert.equal((await state()).studentRooms['demo-0'],secondRoom);await dragPupil('demo-0',firstRoom);assert.equal((await state()).studentRooms['demo-0'],firstRoom);s=await state();
    // Manual assignment stays separate from seats and refuses silent overfilling.
    const originalRoom=s.studentRooms['demo-0'];await js(`document.querySelector('[data-room-action="close-pupil"]')?.click();document.querySelector('[data-room-pupil="demo-0"]').click();document.querySelector('#manual-destination').value='${originalRoom===a.id?b.id:a.id}';document.querySelector('[data-room-action="assign"]').click();`);s=await state();assert.notEqual(s.studentRooms['demo-0'],originalRoom);assert.ok(!s.rooms.some(r=>Object.values(r.assignments).includes('demo-0')));
    const fullRoom=s.studentRooms['demo-0'],otherStudent=s.students.find(p=>s.studentRooms[p.id]!==fullRoom).id;await js(`document.querySelector('[data-room-pupil="${otherStudent}"]').click();document.querySelector('#manual-destination').value='${fullRoom}';document.querySelector('[data-room-action="assign"]').click();`);assert.ok(await js(`document.querySelector('#modal').open`));assert.match(await js(`document.querySelector('#modal-content').textContent`),/overschrijdt de capaciteit/);await js(`document.querySelector('#room-dialog-save').click()`);assert.match(await js(`document.querySelector('.room-overflow').textContent`),/1 leerlingen boven/);
    const activeBeforeAuto=(await state()).activeRoomId;await auto();
    s=await state();assert.equal(new Set(s.rooms.flatMap(r=>Object.values(r.assignments))).size,6);
    assert.equal(await js(`document.querySelector('#navigation [data-tab="distribution"]').classList.contains('active')`),true);
    assert.equal(await js(`document.body.classList.contains('room-management')`),true);
    assert.equal(s.activeRoomId,activeBeforeAuto);
    await js(`document.querySelector('[data-room-open="${a.id}"]').click()`);assert.equal(await js(`document.querySelectorAll('#room .seat').length`),4);assert.equal(await js(`document.querySelectorAll('#room .teacher-bench').length`),1);assert.match(await js(`document.querySelector('.room-top strong').textContent`),/3.12/);await shot('desktop-custom-seating.png');
    const seated=Object.values((await state()).assignments)[0];await js(`document.querySelector('[data-student="${seated}"]').dispatchEvent(new MouseEvent('click',{bubbles:true}));document.querySelector('[data-action="fixed-position"]').click();`);assert.ok(await js(`document.querySelector('#rule-seat').options.length>=2`));await js(`document.querySelector('#rule-submit').click()`);assert.ok((await state()).rules.some(r=>r.type==='fixed'&&r.roomId===a.id));
    const lookupCode=await js(`(async()=>{const e=await import('./engine.mjs'),s=JSON.parse(localStorage.getItem('klaslokaal-v1'));return e.seatCode(Object.keys(s.assignments)[0],s.settings);})()`);
    await js(`document.querySelector('#search').value=${JSON.stringify(lookupCode)};document.querySelector('#search').dispatchEvent(new Event('input'));`);assert.match(await js(`document.querySelector('#search-results').textContent`),/Lokaal/);assert.ok((await js(`document.querySelector('#search-results').textContent`)).includes(lookupCode));
    // Real combined XLSX download, saved only in the isolated test artifact directory.
    const target=path.join(root,'artifacts','desktop-multiroom.xlsx');const downloaded=new Promise((resolve,reject)=>{win.webContents.session.once('will-download',(_e,item)=>{item.setSavePath(target);item.once('done',(_e,status)=>status==='completed'?resolve():reject(Error(status)));});});
    await js(`document.querySelector('[data-tab="distribution"]').click();document.querySelector('[data-tab=export]').click();document.querySelector('#export-scope').value='all';document.querySelector('#export-scope').dispatchEvent(new Event('change'));document.querySelector('#export-submit').click()`);await downloaded;
    const expected=await js(`(async()=>{const e=await import('./excel-export.mjs');return e.seatingRows(JSON.parse(localStorage.getItem('klaslokaal-v1')),{allRooms:true});})()`);await fs.writeFile(path.join(root,'artifacts','desktop-multiroom-expected.json'),JSON.stringify(expected));assert.equal((await fs.readFile(target)).readUInt32LE(0),0x04034b50);
    // Current room, room membership, templates, pins and layout survive a complete reload.
    const before=await state();await win.loadFile(path.join(root,'src','index.html'));const after=await state();assert.deepEqual(after.studentRooms,before.studentRooms);assert.deepEqual(after.rooms,before.rooms);assert.equal(after.roomTemplates.length,1);assert.equal(await js(`document.querySelectorAll('#room .seat').length`),4);
    // Restore original classroom and verify unchanged geometry.
    await js(`document.querySelector('#active-room').value='standaardlokaal';document.querySelector('#active-room').dispatchEvent(new Event('change'))`);assert.equal(await js(`document.querySelectorAll('#room .bench').length`),95);assert.equal(await js(`document.querySelectorAll('#room .seat').length`),190);
    // Delete only a duplicated test room, then undo it with the existing history.
    await js(`document.querySelector('[data-tab="rooms"]').click();document.querySelector('[data-room-delete="${b.id}"]').click();document.querySelector('#room-dialog-save').click()`);assert.equal((await state()).rooms.length,2);await js(`document.querySelector('#undo').click()`);assert.equal((await state()).rooms.length,3);
    if(errors.length)throw Error(errors.join('\n'));
    console.log(JSON.stringify({ok:true,rooms:3,presentStudents:6,customSeats:4,checks:'grid pointer drag, direction, paired capacity, teacher exclusion, undo/redo, duplicate, templates, combined distribution and seating, manual overfill warning, worker generation, pins, fixed positions, persistence, XLSX, default preservation'}));app.exit(0);
  }catch(error){console.error(error);app.exit(1);}
});
