import { benchSize, makeBench, fits, GRID, DIRECTIONS, directionName, customSeatGeometry, layoutSize, layoutValid, benchSeatCode, benchSeatCodes, sectionSeatNames } from './layout.mjs';
import { axisBenchIds, mergeSelection, selectionRect, benchesInRect } from './bench-selection.mjs';
import { generateGrid, gridColumns, columnIndex, columnLetter, columnX, rowY, rowOffset, visualPosition, visualBands, tableAt, setTable, resizeCanvas, removeTable, setGap, setRowGap, setSection, removeSection, migrateGridRoom } from './grid-room.mjs';
const clone=value=>structuredClone(value);
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

export function createGridEditor({host,toast,onSave,onClose}) {
  let draft=null,selected=null,past=[],future=[],drag=null,scroll={left:0,top:0},zoom=.75,placing=null;
  let selection=[],selectionMode=false,selectionLabel='',seatNames=new Map();
  const $=selector=>host.querySelector(selector);
  const change=fn=>{past.push(clone(draft));if(past.length>40)past.shift();future=[];fn();resizeCanvas(draft.layout);render();};
  const attempt=fn=>{try{fn();}catch(error){toast(error.message);}};
  function open(room){draft={id:room.id,name:room.name,layout:migrateGridRoom(room.layout)};draft.layout.benches.forEach(b=>{if(room.settings.disabled.includes(b.id))b.enabled=false;});selected=null;selection=[];selectionMode=false;past=[];future=[];scroll={left:0,top:0};placing=null;render();}
  function boundaries(value){return gridColumns(draft.layout.grid).slice(0,-1).map(c=>`<option value="${c}" ${value===c?'selected':''}>${c}–${columnLetter(columnIndex(c)+1)}</option>`).join('');}
  function render(){
    if(!draft)return;
    seatNames=sectionSeatNames(draft.layout);
    const l=draft.layout,b=l.benches.find(b=>b.id===selected),p=b&&visualPosition(l,b),size=layoutSize(l);
    selection=selection.filter(id=>l.benches.some(b=>b.id===id&&b.kind==='student'));
    const previous=$('.grid-scroll'),expanded=$('.visual-settings')?.open;
    if(previous)scroll={left:previous.scrollLeft,top:previous.scrollTop};
    const ancestors=[];for(let el=host.parentElement;el;el=el.parentElement)ancestors.push([el,el.scrollLeft,el.scrollTop]);
    const page={x:window.scrollX,y:window.scrollY},focus=document.activeElement?.id;
    host.innerHTML=`<div class="rooms-heading"><div><h2>Opstelling · ${esc(draft.name)}</h2></div><button class="button" data-room-action="cancel-edit">Sluiten</button></div>
      <div class="editor-settings grid-generator"><label>Kolommen <input id="grid-from" value="${l.grid.from}" maxlength="2" aria-label="Beginkolom A tot ZZ"> – <input id="grid-to" value="${l.grid.to}" maxlength="2" aria-label="Eindkolom A tot ZZ"></label><label>Tafelrijen <input id="grid-rows" type="number" min="1" max="100" value="${l.grid.rows}"></label><button class="button primary" data-editor-action="generate" title="Kolommen en tafelrijen toepassen (Enter)" aria-label="Kolommen en tafelrijen toepassen">Toepassen</button><span>${l.benches.filter(b=>b.kind==='student').length} banken · ${l.benches.filter(b=>b.kind==='student'&&b.enabled).reduce((n,b)=>n+b.capacity,0)} plaatsen</span></div>
      <details class="visual-settings"><summary>Tussenruimte en eigen vakken <span>${l.gaps.length+(l.rowGaps??[]).length} tussenruimtes · ${l.sections.length} eigen vakken</span></summary><div class="visual-settings-columns"><div><h3>Tussenruimte</h3><label>As<select id="gap-axis"><option value="column">Kolommen</option><option value="row">Rijen</option></select></label><label>Na<select id="gap-after">${boundaries()}</select><select id="row-gap-after" hidden>${Array.from({length:Math.max(0,l.grid.rows-1)},(_,i)=>`<option value="${i+1}">${i+1}–${i+2}</option>`).join('')}</select></label><label>Extra rastervakken<input id="gap-width" type="number" min="0" max="100" value="2"></label><button class="button small" data-editor-action="gap">Bewaren</button>${l.gaps.map(g=>`<div class="visual-item"><span>Kolom ${g.after}–${columnLetter(columnIndex(g.after)+1)} · +${g.width}</span><button class="button small" data-editor-gap="${g.after}">Aanpassen</button><button class="button small" data-editor-remove-gap="${g.after}" aria-label="Tussenruimte verwijderen">×</button></div>`).join('')}${(l.rowGaps??[]).map(g=>`<div class="visual-item"><span>Rij ${g.after}–${g.after+1} · +${g.width}</span><button class="button small" data-editor-row-gap="${g.after}">Aanpassen</button><button class="button small" data-editor-remove-row-gap="${g.after}" aria-label="Rijtussenruimte verwijderen">×</button></div>`).join('')}</div>
      <div><h3>Eigen leeg vak</h3><input id="section-id" type="hidden"><label>Tussen kolommen<select id="section-after">${boundaries()}</select></label><label>Naam<input id="section-name" placeholder="Extra, Computers, Opslag…" maxlength="100"></label><label>Breedte<input id="section-width" type="number" min="6" max="100" value="12"></label><button class="button small" data-editor-action="section">Vak bewaren</button><button class="button small" data-editor-action="new-section">Nieuw vak</button>${l.sections.map(s=>`<div class="visual-item"><span>${esc(s.name)} · ${s.after}–${columnLetter(columnIndex(s.after)+1)} · ${s.width}</span><button class="button small" data-editor-section="${esc(s.id)}">Aanpassen</button><button class="button small" data-editor-remove-section="${esc(s.id)}" aria-label="Vak verwijderen">×</button></div>`).join('')}</div></div><div class="grid-pitch"><label>Kolombreedte<input id="grid-column-step" type="number" min="4" max="100" value="${l.grid.columnStep??6}"></label><label>Rijhoogte<input id="grid-row-step" type="number" min="4" max="100" value="${l.grid.rowStep??6}"></label><label>Eerste rij vanaf<input id="grid-first-row" type="number" min="0" max="100" value="${l.grid.firstRow??6}"></label></div></details>
      <div class="editor-actions"><button class="button ${placing?'primary':''}" data-editor-action="student" aria-pressed="${!!placing}">＋ Bank plaatsen</button><button class="button ${selectionMode?'primary':''}" data-editor-action="select-benches" aria-pressed="${selectionMode}">Meerdere banken</button><button class="button" data-editor-action="teacher">${l.benches.some(b=>b.kind==='teacher')?'Leerkracht selecteren':'＋ Leerkracht plaatsen'}</button><div class="canvas-selection-tools"><button class="button" data-editor-action="rotate" ${!b?'disabled':''} title="R">↻ Draaien</button><button class="button" data-editor-action="copy" ${!b||b.kind==='teacher'?'disabled':''}>Dupliceren</button><button class="button" data-editor-action="delete" ${!b?'disabled':''}>Verwijderen</button></div><button class="button" data-editor-action="undo" ${!past.length?'disabled':''} title="Ctrl+Z">↶</button><button class="button" data-editor-action="redo" ${!future.length?'disabled':''} title="Ctrl+Y">↷</button><label>Zoom <select id="editor-zoom">${[.25,.5,.75,1,1.5].map(z=>`<option value="${z}" ${zoom===z?'selected':''}>${z*100}%</option>`).join('')}</select></label><button class="button primary editor-save" data-editor-action="save">Opslaan</button></div>
      <div id="editor-status" role="status">${placing?'Bank plaatsen':selectionMode?'Meerdere banken':''}</div>
      <div class="editor-layout"><div class="grid-shell"><div class="grid-axis-corner">↘</div><div id="grid-top-axis" class="grid-top-axis"></div><div id="grid-side-axis" class="grid-side-axis"></div><div class="grid-scroll"><svg id="layout-grid" viewBox="0 0 ${size.width} ${size.height}" width="${size.width*zoom}" height="${size.height*zoom}" tabindex="0" class="${placing?'placing':selectionMode?'selecting-benches':''}" aria-label="Lokaalraster; sleep tafels, R draait, pijltoetsen verplaatsen, Delete verwijdert"><defs><pattern id="room-grid-pattern" x="40" y="64" width="32" height="32" patternUnits="userSpaceOnUse"><path d="M 32 0 L 0 0 0 32" fill="none" stroke="#e9efeb" stroke-width="1"/></pattern></defs><rect x="40" y="64" width="${size.width-80}" height="${size.height-112}" fill="url(#room-grid-pattern)" stroke="#a7bbaa"/><g id="grid-content"></g><g id="placement-preview" pointer-events="none"></g><rect id="grid-selection-box" class="selection-box" pointer-events="none" hidden/></svg></div></div>
      <aside class="bench-properties">${selection.length?groupProperties():b?`<h3>${b.kind==='teacher'?'Leerkracht':'Plaatsen '+esc(benchSeatCodes({...b,...seatNames.get(b.id)},l.version).join(' / '))}</h3><p>${b.cell?'Kolom '+esc(b.cell.column):'Handmatig geplaatst'}${b.sectionId?' · '+esc(l.sections.find(s=>s.id===b.sectionId)?.name):''}</p><label>Richting<select id="bench-facing">${DIRECTIONS.map(d=>`<option value="${d}" ${b.facing===d?'selected':''}>${directionName(d)}</option>`).join('')}</select></label>${b.kind==='student'?`<label>Leerlingplaatsen<select id="bench-capacity">${[1,2,...(b.capacity>2?[b.capacity]:[])].map(n=>`<option ${b.capacity===n?'selected':''}>${n}</option>`).join('')}</select></label><label class="toggle-line"><input id="bench-enabled" type="checkbox" ${b.enabled?'checked':''}>Bank ingeschakeld</label>`:''}<details class="table-coordinates"><summary>Precieze positie</summary><div class="range-fields"><label>X<input id="bench-gx" type="number" min="0" value="${p.gx}"></label><label>Y<input id="bench-gy" type="number" min="0" value="${p.gy}"></label></div><button class="button full" data-editor-action="position">Positie instellen</button></details>`:'<h3>Het lokaal bewerken</h3>'}</aside></div>`;
    const viewport=$('.grid-scroll');viewport.scrollLeft=scroll.left;viewport.scrollTop=scroll.top;viewport.onscroll=paint;
    if(expanded)$('.visual-settings').open=true;
    $('#editor-zoom').onchange=e=>{const old=zoom;zoom=Number(e.target.value);scroll={left:viewport.scrollLeft*zoom/old,top:viewport.scrollTop*zoom/old};viewport.scrollLeft=scroll.left;viewport.scrollTop=scroll.top;render();};
    $('#gap-axis').onchange=gapAxis;
    if(b){$('#bench-facing').onchange=e=>update({...b,facing:e.target.value});if($('#bench-capacity'))$('#bench-capacity').onchange=e=>update({...b,capacity:Number(e.target.value)});if($('#bench-enabled'))$('#bench-enabled').onchange=e=>update({...b,enabled:e.target.checked});}
    attach();paint();
    if(focus&&$('#'+focus))$('#'+focus).focus({preventScroll:true});
    for(const [el,left,top] of ancestors){el.scrollLeft=left;el.scrollTop=top;}window.scrollTo(page.x,page.y);
  }
  function gapAxis(){$('#gap-after').hidden=$('#gap-axis').value==='row';$('#row-gap-after').hidden=$('#gap-axis').value!=='row';}
  function groupProperties() {
    const benches=draft.layout.benches.filter(b=>selection.includes(b.id)),enabled=benches.filter(b=>b.enabled).length;
    return `<h3>Meerdere banken</h3><p>${selectionLabel?esc(selectionLabel)+' · ':''}${benches.length} ${benches.length===1?'bank':'banken'} geselecteerd<br>${enabled} actief · ${benches.length-enabled} uitgeschakeld</p><button class="button full" data-editor-action="enable-selected" ${enabled===benches.length?'disabled':''}>Banken activeren</button><button class="button full" data-editor-action="disable-selected" ${!enabled?'disabled':''}>Banken deactiveren</button><button class="button full" data-editor-action="clear-selection">Selectie opheffen</button>`;
  }
  function selectBenches(ids,{additive=false,toggle=false,label=''}={}) {
    selection=mergeSelection(selection.length?selection:selected?[selected]:[],ids,{additive,toggle}).filter(id=>draft.layout.benches.some(b=>b.id===id&&b.kind==='student'));selected=null;selectionLabel=additive?'':label;placing=null;render();
  }
  function visualBenches() {return draft.layout.benches.map(b=>{const p=visualPosition(draft.layout,b);return {...b,x:40+p.gx*GRID,y:64+p.gy*GRID};});}
  function axisSelected(column,row) {const ids=axisBenchIds(draft.layout.benches,column?{column}:{row});return ids.length>0&&ids.every(id=>selection.includes(id));}
  function chooseGap(axis,after){$('.visual-settings').open=true;$('#gap-axis').value=axis;gapAxis();$(axis==='row'?'#row-gap-after':'#gap-after').value=after;$('#gap-width').value=(axis==='row'?draft.layout.rowGaps:draft.layout.gaps)?.find(g=>String(g.after)===String(after))?.width??2;}
  function paint(){
    if(!draft||drag)return;const l=draft.layout,v=$('.grid-scroll');if(!v)return;
    const size=layoutSize(l),left=v.scrollLeft/zoom-200,top=v.scrollTop/zoom-200,right=left+v.clientWidth/zoom+400,bottom=top+v.clientHeight/zoom+400;
    const visible=(x,y,w,h)=>x+w>=left&&x<=right&&y+h>=top&&y<=bottom;
    const columns=gridColumns(l.grid),colPosition=c=>40+visualPosition(l,{gx:columnX(l,c),gy:0,anchor:c}).gx*GRID;
    let guides='';
    for(const c of columns){const x=colPosition(c);if(x>=left&&x<=right)guides+=`<line x1="${x-16}" y1="64" x2="${x-16}" y2="${size.height-48}" class="table-grid-guide"/>`;}
    for(let row=1;row<=l.grid.rows;row++){const y=64+(rowY(l,row)+rowOffset(l,row))*GRID;if(y>=top&&y<=bottom)guides+=`<line x1="40" y1="${y-28}" x2="${size.width-40}" y2="${y-28}" class="table-grid-guide"/>`;}
    for(const g of l.gaps){const x=colPosition(g.after)+(l.grid.columnStep??6)*GRID;if(visible(x,64,g.width*GRID,size.height))guides+=`<rect class="visual-gap" x="${x}" y="64" width="${g.width*GRID}" height="${size.height-112}"/><text x="${x+g.width*GRID/2}" y="120" class="gap-label" text-anchor="middle">+${g.width}</text>`;}
    for(const g of l.rowGaps??[]){const y=64+(rowY(l,g.after+1)+rowOffset(l,g.after+1)-g.width)*GRID-28;guides+=`<rect class="visual-gap" x="40" y="${y}" width="${size.width-80}" height="${g.width*GRID}"/><text x="50" y="${y+18}" class="gap-label">+${g.width}</text>`;}
    const bands=visualBands(l),sections=bands.filter(s=>visible(40+s.x*GRID,64,s.width*GRID,size.height)).map(s=>`<g class="custom-section"><rect x="${40+s.x*GRID}" y="64" width="${s.width*GRID}" height="${size.height-112}" fill="#edf4fa" fill-opacity=".8" stroke="#b8cde0"/><text x="${48+s.x*GRID}" y="88" font-size="17" fill="#54768c">${esc(s.name)}</text></g>`).join('');
    $('#grid-content').innerHTML=guides+sections+l.benches.filter(b=>{const p=visualPosition(l,b),s=benchSize(b);return visible(40+p.gx*GRID,64+p.gy*GRID,s.width,s.height);}).map(b=>object(b)).join('');
    // Axes are outside the scrolling surface, so they remain visible at every zoom.
    $('#grid-top-axis').innerHTML=`<svg width="${size.width*zoom}" height="30" style="transform:translateX(${-v.scrollLeft}px)">${columns.filter(c=>visible(colPosition(c),top,192,1)).map(c=>`<g data-axis-column="${c}" role="button" tabindex="0" aria-label="Kolom ${c}: banken selecteren" aria-pressed="${axisSelected(c)}" class="axis-label ${axisSelected(c)?'axis-selected':''}"><rect x="${colPosition(c)*zoom}" width="${(l.grid.columnStep??6)*GRID*zoom}" height="30"/><text x="${(colPosition(c)+((l.grid.columnStep??6)*GRID)/2)*zoom}" y="20" text-anchor="middle">${c}</text></g>`).join('')}${bands.map(s=>`<text class="area-axis-label" x="${(40+(s.x+s.width/2)*GRID)*zoom}" y="20" text-anchor="middle">${esc(s.name)}</text>`).join('')}${l.gaps.map(g=>`<text class="axis-gap-label" x="${(colPosition(g.after)+((l.grid.columnStep??6)+g.width/2)*GRID)*zoom}" y="20" text-anchor="middle">+${g.width}</text>`).join('')}</svg>`;
    $('#grid-side-axis').innerHTML=`<svg width="52" height="${size.height*zoom}" style="transform:translateY(${-v.scrollTop}px)">${Array.from({length:l.grid.rows},(_,i)=>{const y=(64+(rowY(l,i+1)+rowOffset(l,i+1))*GRID)*zoom;return `<g data-axis-row="${i+1}">${[43,96].map((offset,j)=>{const row=i*2+j+1,center=y+offset*zoom,active=axisSelected(null,row);return `<g class="axis-label ${active?'axis-selected':''}" data-axis-seat-row="${row}" role="button" tabindex="0" aria-label="Stoelrij ${row}: banken selecteren" aria-pressed="${active}"><rect y="${center-15}" width="52" height="${Math.min(26,53*zoom)}"/><text x="18" y="${center}" text-anchor="middle">${row}</text></g>`;}).join('')}</g>`;}).join('')}</svg>`;
  }
  function object(b,names=seatNames){b={...b,...names.get(b.id)};const p=visualPosition(draft.layout,b),bench={...b,x:40+p.gx*GRID,y:64+p.gy*GRID},s=benchSize(b);return `<g data-grid-bench="${b.id}" class="grid-bench ${b.id===selected||selection.includes(b.id)?'chosen':''} ${!b.enabled?'off':''}"><title>${esc(b.kind==='teacher'?'Leerkracht':benchSeatCodes(b,draft.layout.version).join(' / '))} · ${b.capacity} ${b.kind==='teacher'?'stoel':'plaatsen'}</title><rect class="grid-table" x="${bench.x}" y="${bench.y}" width="${s.width}" height="${s.height}" rx="5" fill="${b.kind==='teacher'?'#d76b62':'#e9e7dc'}" stroke="#a4b19d" stroke-width="2"/>${Array.from({length:b.capacity},(_,i)=>{const g=customSeatGeometry(bench,i);return `<rect class="grid-chair" x="${g.chairX}" y="${g.chairY}" width="${g.chairWidth}" height="${g.chairHeight}" rx="4" fill="#a6b0b3"/><text class="grid-seat-code" data-code="${b.kind==='teacher'?'':esc(benchSeatCode(b,i,draft.layout.version))}" x="${g.x+g.w/2}" y="${g.y+25}" text-anchor="middle" font-size="12" fill="${b.kind==='teacher'?'white':'#738373'}">${b.kind==='teacher'?'Leerkracht':esc(benchSeatCode(b,i,draft.layout.version))}</text>`;}).join('')}<text x="${bench.x+s.width-8}" y="${bench.y+s.height-8}" text-anchor="end" font-size="15" fill="${b.kind==='teacher'?'white':'#476b57'}">${{up:'↑',right:'→',down:'↓',left:'←'}[b.facing]}</text></g>`;}
  function update(next){const previous=draft.layout.benches.find(b=>b.id===next.id),positionChanged=['gx','gy','anchor','rowAnchor','sectionId','code'].some(key=>next[key]!==previous?.[key]);if(positionChanged&&!fits(draft.layout,next))return toast('Deze tafel overlapt een andere tafel of past niet in het gekozen vak. Kies een vrije positie.');if(next.sectionId){const section=draft.layout.sections.find(s=>s.id===next.sectionId);if(next.gx*GRID+benchSize(next).width>section.width*GRID)return toast('De gedraaide tafel past niet in dit vak. Verplaats haar of maak het vak breder.');}change(()=>setTable(draft.layout,next));}
  function at(b,p){return tableAt(draft.layout,b,p.gx,p.gy);}
  function placementAt(p){const b=at(placing,p);if(b.kind==='student'&&b.cell){const peer=draft.layout.benches.find(other=>other.kind==='student'&&other.cell?.column===b.cell.column)??draft.layout.benches.find(other=>other.kind==='student'&&other.cell);if(peer)b.facing=peer.facing;}return b;}
  function point(e){const p=new DOMPoint(e.clientX,e.clientY).matrixTransform($('#layout-grid').getScreenCTM().inverse());return {gx:Math.max(0,Math.round((p.x-40)/GRID)),gy:Math.max(0,Math.round((p.y-64)/GRID))};}
  function canvasPoint(e){return new DOMPoint(e.clientX,e.clientY).matrixTransform($('#layout-grid').getScreenCTM().inverse());}
  function place(p){const b=placementAt(p);if(!fits(draft.layout,b))return toast('Kies een vrije plek; deze tafel overlapt een andere tafel.');change(()=>{setTable(draft.layout,b);draft.layout.nextManual++;selected=b.id;placing=null;});$('#layout-grid').focus({preventScroll:true});}
  function preview(p){const b=placementAt(p);$('#placement-preview').innerHTML=object(b,sectionSeatNames(draft.layout,b));$('#placement-preview').classList.toggle('invalid',!fits(draft.layout,b));}
  function attach(){const svg=$('#layout-grid');
    svg.onpointerdown=e=>{if(e.button!==0)return;const el=e.target.closest('[data-grid-bench]'),p=point(e);if(placing){e.preventDefault();place(p);return;}
      if(!el||selectionMode||e.ctrlKey||e.metaKey){drag={kind:'selection',start:canvasPoint(e),x:e.clientX,y:e.clientY,moved:false,bench:el?.dataset.gridBench,base:[...(selection.length?selection:selected?[selected]:[])],additive:e.ctrlKey||e.metaKey||selectionMode};svg.setPointerCapture(e.pointerId);e.preventDefault();return;}
      selection=[];selected=el.dataset.gridBench;const b=draft.layout.benches.find(b=>b.id===selected);drag={origin:clone(b),visual:visualPosition(draft.layout,b),start:p,moved:false};svg.querySelectorAll('.chosen').forEach(el=>el.classList.remove('chosen'));el.classList.add('chosen');svg.setPointerCapture(e.pointerId);e.preventDefault();};
    svg.onpointermove=e=>{const p=point(e);if(placing){preview(p);return;}if(!drag)return;
      if(drag.kind==='selection'){if(Math.hypot(e.clientX-drag.x,e.clientY-drag.y)>6)drag.moved=true;if(drag.moved){const rect=selectionRect(drag.start,canvasPoint(e)),box=$('#grid-selection-box');box.removeAttribute('hidden');for(const [key,value] of Object.entries(rect))box.setAttribute(key,value);const ids=mergeSelection(drag.base,benchesInRect(visualBenches(),rect),{additive:drag.additive});svg.querySelectorAll('[data-grid-bench]').forEach(el=>el.classList.toggle('chosen',ids.includes(el.dataset.gridBench)));}return;}
      const gx=Math.max(0,drag.visual.gx+p.gx-drag.start.gx),gy=Math.max(0,drag.visual.gy+p.gy-drag.start.gy);drag.next=at(drag.origin,{gx,gy});drag.moved=gx!==drag.visual.gx||gy!==drag.visual.gy;const el=svg.querySelector(`[data-grid-bench="${drag.origin.id}"]`);if(drag.moved){const preview=$('#placement-preview');preview.innerHTML=object(drag.next,sectionSeatNames(draft.layout,drag.next));preview.classList.toggle('invalid',!fits(draft.layout,drag.next));el.style.opacity='.25';}};
    svg.onpointerup=e=>{if(!drag)return;const d=drag;drag=null;if(svg.hasPointerCapture(e.pointerId))svg.releasePointerCapture(e.pointerId);
      if(d.kind==='selection'){selection=d.base;selected=null;if(d.moved)selectBenches(benchesInRect(visualBenches(),selectionRect(d.start,canvasPoint(e))),{additive:d.additive});else if(d.bench&&draft.layout.benches.find(b=>b.id===d.bench)?.kind==='student')selectBenches([d.bench],{additive:d.additive,toggle:d.additive});else if(!d.additive)selectBenches([]);else render();$('#layout-grid').focus({preventScroll:true});return;}
      if(d.moved)update(d.next);render();$('#layout-grid').focus({preventScroll:true});};
    svg.onpointercancel=()=>{drag=null;render();};
    svg.onkeydown=e=>{if(e.key==='Escape'){placing=null;selection=[];selectionMode=false;drag=null;render();return;}const b=draft.layout.benches.find(b=>b.id===selected);if(!b)return;const delta={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]}[e.key];if(delta){e.preventDefault();const l=draft.layout,p=visualPosition(l,b),stepX=b.kind==='student'&&!b.sectionId?(l.grid.columnStep??6):1,stepY=b.kind==='student'&&!b.sectionId?(l.grid.rowStep??6):1;let gx=p.gx+delta[0]*stepX,gy=p.gy+delta[1]*stepY;if(b.cell){const column=columnLetter(columnIndex(b.cell.column)+delta[0]),row=b.cell.row+delta[1];if(columnIndex(column)<columnIndex(l.grid.from)||columnIndex(column)>columnIndex(l.grid.to)||row<1||row>l.grid.rows)return;const target=visualPosition(l,{gx:columnX(l,column),gy:rowY(l,row),anchor:column,rowAnchor:row});gx=target.gx;gy=target.gy;}update(at(b,{gx,gy}));$('#layout-grid').focus({preventScroll:true});}if(e.key.toLowerCase()==='r'){e.preventDefault();action('rotate');}if(e.key==='Delete'){e.preventDefault();action('delete');}};
    // A new table can also be dragged from the toolbar directly onto the canvas.
    const addButton=$('[data-editor-action="student"]');addButton.onpointerdown=e=>{if(e.button!==0)return;const start={x:e.clientX,y:e.clientY};let moved=false;const move=ev=>{if(Math.hypot(ev.clientX-start.x,ev.clientY-start.y)<6&&!moved)return;moved=true;placing??=makeBench(draft.layout);const rect=svg.getBoundingClientRect();if(ev.clientX>=rect.left&&ev.clientY>=rect.top&&ev.clientX<=rect.right&&ev.clientY<=rect.bottom)preview(point(ev));};const up=ev=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);if(!moved)return;ev.preventDefault();const rect=$('.grid-scroll').getBoundingClientRect();if(ev.clientX>=rect.left&&ev.clientX<=rect.right&&ev.clientY>=rect.top&&ev.clientY<=rect.bottom)place(point(ev));else render();};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up,{once:true});};
  }
  function duplicate(b){const bench=makeBench(draft.layout,'student',{capacity:b.capacity,facing:b.facing}),origin=visualPosition(draft.layout,b);let next=null;
    // Search outward from the selected table, keeping the copy close to its source.
    outer:for(let radius=1;radius<Math.max(draft.layout.columns,draft.layout.rows)+12;radius++){for(let dy=-radius;dy<=radius;dy++)for(const dx of dy===-radius||dy===radius?Array.from({length:radius*2+1},(_,i)=>i-radius):[-radius,radius]){const gx=origin.gx+dx,gy=origin.gy+dy;if(gx<0||gy<0)continue;const candidate=at(bench,{gx,gy});if(fits(draft.layout,candidate)){next=candidate;break outer;}}}
    if(!next)return toast('Geen vrije plek voor een kopie. Maak extra ruimte.');
    change(()=>{setTable(draft.layout,next);draft.layout.nextManual++;selected=next.id;});
  }
  function action(name){if(!draft)return;const b=draft.layout.benches.find(b=>b.id===selected);
    if(name==='select-benches'){selectionMode=!selectionMode;selected=null;placing=null;render();return;}
    if(name==='clear-selection'){selection=[];selectionMode=false;render();return;}
    if(['enable-selected','disable-selected'].includes(name)){if(selection.length)change(()=>{for(const b of draft.layout.benches)if(b.kind==='student'&&selection.includes(b.id))b.enabled=name==='enable-selected';});return;}
    if(name==='generate')return attempt(()=>{const grid={from:$('#grid-from').value.trim().toUpperCase(),to:$('#grid-to').value.trim().toUpperCase(),rows:Number($('#grid-rows').value)};for(const [key,id,base] of [['columnStep','grid-column-step',6],['rowStep','grid-row-step',6],['firstRow','grid-first-row',6]]){const value=Number($('#'+id).value);if(!Number.isInteger(value)||value<(key==='firstRow'?0:4)||value>100)throw Error('Kies geldige rastermaten van 4–100; de eerste rij mag vanaf 0 beginnen.');if(value!==base||draft.layout.grid[key]!==undefined)grid[key]=value;}const next=generateGrid(draft.layout,grid,{fitCanvas:true});change(()=>draft.layout=next);});
    if(name==='gap')return attempt(()=>{const next=clone(draft.layout);if($('#gap-axis').value==='row')setRowGap(next,Number($('#row-gap-after').value),Number($('#gap-width').value));else setGap(next,$('#gap-after').value,Number($('#gap-width').value));change(()=>draft.layout=next);});
    if(name==='section')return attempt(()=>{const next=clone(draft.layout);setSection(next,{id:$('#section-id').value||undefined,after:$('#section-after').value,name:$('#section-name').value,width:Number($('#section-width').value)});change(()=>draft.layout=next);});
    if(name==='new-section'){$('#section-id').value='';$('#section-name').value='';$('#section-width').value=12;return;}
    if(name==='student'){selection=[];selectionMode=false;placing=placing?null:makeBench(draft.layout);render();if(placing)$('#layout-grid').focus({preventScroll:true});return;}
    if(name==='teacher'){selection=[];selectionMode=false;const teacher=draft.layout.benches.find(b=>b.kind==='teacher');if(teacher){placing=null;selected=teacher.id;render();const p=visualPosition(draft.layout,teacher),v=$('.grid-scroll');v.scrollTo({left:Math.max(0,(40+p.gx*GRID)*zoom-v.clientWidth/2),top:Math.max(0,(64+p.gy*GRID)*zoom-v.clientHeight/2)});paint();}else{placing=makeBench(draft.layout,'teacher');render();}return;}
    if(['undo','redo'].includes(name)){const source=name==='undo'?past:future,dest=name==='undo'?future:past;if(source.length){dest.push(clone(draft));draft=source.pop();placing=null;render();}return;}
    if(name==='save'){if(!layoutValid(draft.layout))return toast('Controleer de opstelling voordat je bewaart.');const saved=clone(draft);draft=null;onSave(saved);return;}
    if(!b)return;
    if(name==='rotate')return update({...b,facing:DIRECTIONS[(DIRECTIONS.indexOf(b.facing)+1)%4]});
    if(name==='position')return update(at(b,{gx:Number($('#bench-gx').value),gy:Number($('#bench-gy').value)}));
    if(name==='copy')return duplicate(b);
    if(name==='delete')change(()=>{removeTable(draft.layout,b.id);selected=null;});
  }
  host.addEventListener('click',e=>{if(!draft)return;const t=e.target.closest('[data-axis-column],[data-axis-seat-row],button');if(!t)return;
    if(t.dataset.axisColumn||t.dataset.axisSeatRow){const column=t.dataset.axisColumn,row=Number(t.dataset.axisSeatRow);selectBenches(axisBenchIds(draft.layout.benches,column?{column}:{row}),{additive:e.ctrlKey||e.metaKey,label:column?`Kolom ${column}`:`Stoelrij ${row}`});$(column?`[data-axis-column="${column}"]`:`[data-axis-seat-row="${row}"]`)?.focus({preventScroll:true});return;}
    if(t.dataset.editorGap)chooseGap('column',t.dataset.editorGap);
    if(t.dataset.editorRowGap)chooseGap('row',t.dataset.editorRowGap);
    if(t.dataset.editorRemoveGap)change(()=>setGap(draft.layout,t.dataset.editorRemoveGap,0));
    if(t.dataset.editorRemoveRowGap)change(()=>setRowGap(draft.layout,Number(t.dataset.editorRemoveRowGap),0));
    if(t.dataset.editorSection){const s=draft.layout.sections.find(s=>s.id===t.dataset.editorSection);$('#section-id').value=s.id;$('#section-name').value=s.name;$('#section-after').value=s.after;$('#section-width').value=s.width;}
    if(t.dataset.editorRemoveSection)change(()=>removeSection(draft.layout,t.dataset.editorRemoveSection));
  });
  host.addEventListener('keydown',e=>{if(draft&&e.key==='Enter'&&e.target.matches('#grid-from,#grid-to,#grid-rows,#grid-column-step,#grid-row-step,#grid-first-row')){e.preventDefault();action('generate');return;}const axis=e.target.closest('[data-axis-column],[data-axis-seat-row]');if(axis&&['Enter',' '].includes(e.key)){e.preventDefault();axis.dispatchEvent(new MouseEvent('click',{bubbles:true,ctrlKey:e.ctrlKey,metaKey:e.metaKey}));}if(draft&&e.key==='Escape'&&(placing||selection.length||selectionMode)){placing=null;selection=[];selectionMode=false;render();}});
  return {open,render,action,close:()=>{draft=null;placing=null;onClose();},get dirty(){return past.length>0;}};
}
